name: Sync Fork with Upstream

on:
  schedule:
    # This will run every 50 min
    - cron: '*/50 * * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: jovmarkovic/netdata
          token: ${{ secrets.FORK_SYNC }}  
          fetch-depth: 0

      - name: Set Git user details
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      - name: Add upstream remote
        run: |
          if ! git remote get-url upstream 2>/dev/null; then
            git remote add upstream https://github.com/netdata/netdata.git
          fi
          git fetch upstream
          
      - name: Sync master branch
        run: |
          git checkout --track origin/master
          git merge upstream/master
          git push origin master
      
      - name: Merge master with nvme_raid 
        run: |
          git checkout nvme_raid
          git merge origin/master -m "sync-fork workflow: Merge branch 'netdata:master' into nvme_raid"
          git push origin nvme_raid
          
