name: Sync Fork with Upstream

on:
  schedule:
    # This will run every 10 min
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the forked repository
      - name: Checkout repository
        uses: actions/checkout@v3
          
      # Fetch and fast-forward merge changes into the master branch
      - name: Sync master branch
        run: |
          git fetch upstream
          git checkout master
          git merge --ff-only upstream/master
          git push origin master
      
      # Fetch and fast-forward merge changes into the nvme_raid branch
      - name: Sync nvme_raid branch
        run: |
          git checkout nvme_raid
          git merge --ff-only master --allow-unrelated-histories
          git push origin nvme_raid


